version: "3.7"

services:
    webapp:
        image: nginx:latest
        ports:
            - "4000:80"
        volumes:
            - ./:/app
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./:/app
        depends_on:
            - postgres

    postgres:
        image: postgres:14-alpine
        ports:
            - "4001:5432"
        volumes:
            - ./docker/storage/postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: root
            POSTGRES_DB: doodleverse

    pgadmin:
        image: dpage/pgadmin4
        user: root
        ports:
            - "4002:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            PGADMIN_DEFAULT_EMAIL: dev@mail.ru
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - ./docker/storage/pgadmin-data:/var/lib/pgadmin
    #        depends_on:
    #            - postgres
